server.port=8081
logging.level.root=DEBUG
build.id=1
build.version=1.0.1
build.name={cipher}AQA8W92RyV+/hA/XukqKz4D7tFHPKxz8Ovm+L/5xk6QNikPOdD1Y0o6PU6tK4XoV1tg5MjGkPlcBEY1Y+Izrqxht1w30Iehy41e07QoV+nkve6hM7dV7hz8V0rAd5nALm1vEiuR5hTIDvwcgNYv7Pcf8QVHcFZUTh489sCbpUshudmoAcz60fU96bXjF8l/VGY23oQuODy0cNuNYN/qSy9lYcrBYEkbRapATaoLWfSWPWfX99Q7Mdbc5t5zIvQ/VD91y7M4dxQF2E29/ntjYBLMIzEOc8e1+HkYloQAU8Sa22rXhd9OmTDUa/fKqbgaJqx1L7qOAiZENR5I8ZadSX4INL5mz+3kQRSfefB6B9tB/psQ0o10vhEYsD/8Atqwf80c=
build.type=Git Employee Service Build
spring.datasource.password={cipher}22ede38be5d31e2d98f15409434d5c75e038f1a4531dfc4b39d46c393ada23da
