server.port=8081
logging.level.root=INFO
build.id=1
build.verions=1.0.0
build.name="Employee Service Production"
build.type="Git Employee Service Build"
spring.datasource.password={cipher}60a225bb82843c716aa8a590eb36532f138fde76d03a332272aea89efdd68004
