server.port=8081
logging.level.root=DEBUG
build.id=1
build.verion=1.0.0
build.name="Employee Service Dev"
build.type="Git Employee Service Build"
spring.datasource.password={cipher}22ede38be5d31e2d98f15409434d5c75e038f1a4531dfc4b39d46c393ada23da
