server.port=8081
logging.level.root=INFO
build.id=1
build.verion=1.0.0
build.name="Employee Service Production"
build.type="Git Employee Service Build"
spring.datasource.password={cipher}5dc4be84a353b2cf0a70dc4a099c9684b3ea008fa13db1c992e5fe7cddfa2f8f1cb1d2b3fcf75bcc2ae9ee05e29c3fe1
